sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - cd psw-isa
  - chmod +x ./mvnw

script:
  - ./mvnw clean install -DskipTests=true -B

dist: trusty

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: clinical-center-tim31
